// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IncrementClient is the client API for Increment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IncrementClient interface {
	NewNode(ctx context.Context, in *NewNodeRequest, opts ...grpc.CallOption) (*NewNodeReply, error)
	NewIncrement(ctx context.Context, in *NewIncrementRequest, opts ...grpc.CallOption) (*NewIncrementReply, error)
	NewUpdateNumbers(ctx context.Context, in *NewUpdateNumbersRequest, opts ...grpc.CallOption) (*NewUpdateNumbersReply, error)
}

type incrementClient struct {
	cc grpc.ClientConnInterface
}

func NewIncrementClient(cc grpc.ClientConnInterface) IncrementClient {
	return &incrementClient{cc}
}

func (c *incrementClient) NewNode(ctx context.Context, in *NewNodeRequest, opts ...grpc.CallOption) (*NewNodeReply, error) {
	out := new(NewNodeReply)
	err := c.cc.Invoke(ctx, "/communication.Increment/NewNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incrementClient) NewIncrement(ctx context.Context, in *NewIncrementRequest, opts ...grpc.CallOption) (*NewIncrementReply, error) {
	out := new(NewIncrementReply)
	err := c.cc.Invoke(ctx, "/communication.Increment/NewIncrement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incrementClient) NewUpdateNumbers(ctx context.Context, in *NewUpdateNumbersRequest, opts ...grpc.CallOption) (*NewUpdateNumbersReply, error) {
	out := new(NewUpdateNumbersReply)
	err := c.cc.Invoke(ctx, "/communication.Increment/NewUpdateNumbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IncrementServer is the server API for Increment service.
// All implementations must embed UnimplementedIncrementServer
// for forward compatibility
type IncrementServer interface {
	NewNode(context.Context, *NewNodeRequest) (*NewNodeReply, error)
	NewIncrement(context.Context, *NewIncrementRequest) (*NewIncrementReply, error)
	NewUpdateNumbers(context.Context, *NewUpdateNumbersRequest) (*NewUpdateNumbersReply, error)
	mustEmbedUnimplementedIncrementServer()
}

// UnimplementedIncrementServer must be embedded to have forward compatible implementations.
type UnimplementedIncrementServer struct {
}

func (UnimplementedIncrementServer) NewNode(context.Context, *NewNodeRequest) (*NewNodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewNode not implemented")
}
func (UnimplementedIncrementServer) NewIncrement(context.Context, *NewIncrementRequest) (*NewIncrementReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewIncrement not implemented")
}
func (UnimplementedIncrementServer) NewUpdateNumbers(context.Context, *NewUpdateNumbersRequest) (*NewUpdateNumbersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewUpdateNumbers not implemented")
}
func (UnimplementedIncrementServer) mustEmbedUnimplementedIncrementServer() {}

// UnsafeIncrementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IncrementServer will
// result in compilation errors.
type UnsafeIncrementServer interface {
	mustEmbedUnimplementedIncrementServer()
}

func RegisterIncrementServer(s grpc.ServiceRegistrar, srv IncrementServer) {
	s.RegisterService(&Increment_ServiceDesc, srv)
}

func _Increment_NewNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementServer).NewNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Increment/NewNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementServer).NewNode(ctx, req.(*NewNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Increment_NewIncrement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewIncrementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementServer).NewIncrement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Increment/NewIncrement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementServer).NewIncrement(ctx, req.(*NewIncrementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Increment_NewUpdateNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewUpdateNumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementServer).NewUpdateNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/communication.Increment/NewUpdateNumbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementServer).NewUpdateNumbers(ctx, req.(*NewUpdateNumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Increment_ServiceDesc is the grpc.ServiceDesc for Increment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Increment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "communication.Increment",
	HandlerType: (*IncrementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewNode",
			Handler:    _Increment_NewNode_Handler,
		},
		{
			MethodName: "NewIncrement",
			Handler:    _Increment_NewIncrement_Handler,
		},
		{
			MethodName: "NewUpdateNumbers",
			Handler:    _Increment_NewUpdateNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Increment/protobuf/communication.proto",
}
