// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: Increment/protobuf/communication.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewNodeRequest) Reset() {
	*x = NewNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Increment_protobuf_communication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewNodeRequest) ProtoMessage() {}

func (x *NewNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Increment_protobuf_communication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewNodeRequest.ProtoReflect.Descriptor instead.
func (*NewNodeRequest) Descriptor() ([]byte, []int) {
	return file_Increment_protobuf_communication_proto_rawDescGZIP(), []int{0}
}

type NewNodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewNodeReply) Reset() {
	*x = NewNodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Increment_protobuf_communication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewNodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewNodeReply) ProtoMessage() {}

func (x *NewNodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_Increment_protobuf_communication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewNodeReply.ProtoReflect.Descriptor instead.
func (*NewNodeReply) Descriptor() ([]byte, []int) {
	return file_Increment_protobuf_communication_proto_rawDescGZIP(), []int{1}
}

type NewIncrementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewIncrementRequest) Reset() {
	*x = NewIncrementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Increment_protobuf_communication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewIncrementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewIncrementRequest) ProtoMessage() {}

func (x *NewIncrementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Increment_protobuf_communication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewIncrementRequest.ProtoReflect.Descriptor instead.
func (*NewIncrementRequest) Descriptor() ([]byte, []int) {
	return file_Increment_protobuf_communication_proto_rawDescGZIP(), []int{2}
}

type NewIncrementReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer int64 `protobuf:"varint,1,opt,name=answer,proto3" json:"answer,omitempty"`
}

func (x *NewIncrementReply) Reset() {
	*x = NewIncrementReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Increment_protobuf_communication_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewIncrementReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewIncrementReply) ProtoMessage() {}

func (x *NewIncrementReply) ProtoReflect() protoreflect.Message {
	mi := &file_Increment_protobuf_communication_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewIncrementReply.ProtoReflect.Descriptor instead.
func (*NewIncrementReply) Descriptor() ([]byte, []int) {
	return file_Increment_protobuf_communication_proto_rawDescGZIP(), []int{3}
}

func (x *NewIncrementReply) GetAnswer() int64 {
	if x != nil {
		return x.Answer
	}
	return 0
}

type NewUpdateNumbersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdatedNumber int64 `protobuf:"varint,1,opt,name=updatedNumber,proto3" json:"updatedNumber,omitempty"`
}

func (x *NewUpdateNumbersRequest) Reset() {
	*x = NewUpdateNumbersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Increment_protobuf_communication_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewUpdateNumbersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUpdateNumbersRequest) ProtoMessage() {}

func (x *NewUpdateNumbersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Increment_protobuf_communication_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUpdateNumbersRequest.ProtoReflect.Descriptor instead.
func (*NewUpdateNumbersRequest) Descriptor() ([]byte, []int) {
	return file_Increment_protobuf_communication_proto_rawDescGZIP(), []int{4}
}

func (x *NewUpdateNumbersRequest) GetUpdatedNumber() int64 {
	if x != nil {
		return x.UpdatedNumber
	}
	return 0
}

type NewUpdateNumbersReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewUpdateNumbersReply) Reset() {
	*x = NewUpdateNumbersReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Increment_protobuf_communication_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewUpdateNumbersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUpdateNumbersReply) ProtoMessage() {}

func (x *NewUpdateNumbersReply) ProtoReflect() protoreflect.Message {
	mi := &file_Increment_protobuf_communication_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUpdateNumbersReply.ProtoReflect.Descriptor instead.
func (*NewUpdateNumbersReply) Descriptor() ([]byte, []int) {
	return file_Increment_protobuf_communication_proto_rawDescGZIP(), []int{5}
}

var File_Increment_protobuf_communication_proto protoreflect.FileDescriptor

var file_Increment_protobuf_communication_proto_rawDesc = []byte{
	0x0a, 0x26, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x10, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x4e, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x4e, 0x65, 0x77,
	0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x0a, 0x13, 0x4e, 0x65, 0x77,
	0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x2b, 0x0a, 0x11, 0x4e, 0x65, 0x77, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x3f, 0x0a,
	0x17, 0x4e, 0x65, 0x77, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x17,
	0x0a, 0x15, 0x4e, 0x65, 0x77, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0x90, 0x02, 0x0a, 0x09, 0x49, 0x6e, 0x63, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x47, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x1d, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x4e, 0x65, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x4e, 0x65, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x56,
	0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x22,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4e,
	0x65, 0x77, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x4e, 0x65, 0x77, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x10, 0x4e, 0x65, 0x77, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x26, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x65, 0x77, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x4e, 0x65, 0x77, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x68, 0x74,
	0x74, 0x70, 0x3a, 0x2f, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Increment_protobuf_communication_proto_rawDescOnce sync.Once
	file_Increment_protobuf_communication_proto_rawDescData = file_Increment_protobuf_communication_proto_rawDesc
)

func file_Increment_protobuf_communication_proto_rawDescGZIP() []byte {
	file_Increment_protobuf_communication_proto_rawDescOnce.Do(func() {
		file_Increment_protobuf_communication_proto_rawDescData = protoimpl.X.CompressGZIP(file_Increment_protobuf_communication_proto_rawDescData)
	})
	return file_Increment_protobuf_communication_proto_rawDescData
}

var file_Increment_protobuf_communication_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_Increment_protobuf_communication_proto_goTypes = []interface{}{
	(*NewNodeRequest)(nil),          // 0: communication.NewNodeRequest
	(*NewNodeReply)(nil),            // 1: communication.NewNodeReply
	(*NewIncrementRequest)(nil),     // 2: communication.NewIncrementRequest
	(*NewIncrementReply)(nil),       // 3: communication.NewIncrementReply
	(*NewUpdateNumbersRequest)(nil), // 4: communication.NewUpdateNumbersRequest
	(*NewUpdateNumbersReply)(nil),   // 5: communication.NewUpdateNumbersReply
}
var file_Increment_protobuf_communication_proto_depIdxs = []int32{
	0, // 0: communication.Increment.NewNode:input_type -> communication.NewNodeRequest
	2, // 1: communication.Increment.NewIncrement:input_type -> communication.NewIncrementRequest
	4, // 2: communication.Increment.NewUpdateNumbers:input_type -> communication.NewUpdateNumbersRequest
	1, // 3: communication.Increment.NewNode:output_type -> communication.NewNodeReply
	3, // 4: communication.Increment.NewIncrement:output_type -> communication.NewIncrementReply
	5, // 5: communication.Increment.NewUpdateNumbers:output_type -> communication.NewUpdateNumbersReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Increment_protobuf_communication_proto_init() }
func file_Increment_protobuf_communication_proto_init() {
	if File_Increment_protobuf_communication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Increment_protobuf_communication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Increment_protobuf_communication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewNodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Increment_protobuf_communication_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewIncrementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Increment_protobuf_communication_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewIncrementReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Increment_protobuf_communication_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewUpdateNumbersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Increment_protobuf_communication_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewUpdateNumbersReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Increment_protobuf_communication_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Increment_protobuf_communication_proto_goTypes,
		DependencyIndexes: file_Increment_protobuf_communication_proto_depIdxs,
		MessageInfos:      file_Increment_protobuf_communication_proto_msgTypes,
	}.Build()
	File_Increment_protobuf_communication_proto = out.File
	file_Increment_protobuf_communication_proto_rawDesc = nil
	file_Increment_protobuf_communication_proto_goTypes = nil
	file_Increment_protobuf_communication_proto_depIdxs = nil
}
